services:
  backend-staging:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: klassenzeit-backend-staging
    env_file: .env.staging
    environment:
      LOCO_ENV: staging
    networks:
      - web
    restart: unless-stopped

  frontend-staging:
    build:
      context: frontend/
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://klassenzeit-staging.pascalkraus.com
        NEXT_PUBLIC_KEYCLOAK_URL: https://klassenzeit-auth.pascalkraus.com
        NEXT_PUBLIC_KEYCLOAK_REALM: klassenzeit
        NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: klassenzeit-staging
    container_name: klassenzeit-frontend-staging
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
