"""add scheduling tables

Revision ID: aecd2cfdd285
Revises: cc82ebf6c624
Create Date: 2026-04-12 16:12:15.512367

Creates all twelve scheduling domain tables: week_schemes, time_blocks,
subjects, rooms, room_subject_suitabilities, room_availabilities, teachers,
teacher_qualifications, teacher_availabilities, stundentafeln,
stundentafel_entries, school_classes, lessons, and class_groups.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aecd2cfdd285"
down_revision: str | Sequence[str] | None = "cc82ebf6c624"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("short_name", sa.String(length=20), nullable=False),
        sa.Column("capacity", sa.SmallInteger(), nullable=True),
        sa.Column(
            "suitability_mode", sa.String(length=16), server_default="general", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rooms")),
        sa.UniqueConstraint("name", name=op.f("uq_rooms_name")),
        sa.UniqueConstraint("short_name", name=op.f("uq_rooms_short_name")),
    )
    op.create_table(
        "stundentafeln",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("grade_level", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stundentafeln")),
        sa.UniqueConstraint("name", name=op.f("uq_stundentafeln_name")),
    )
    op.create_table(
        "subjects",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("short_name", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subjects")),
        sa.UniqueConstraint("name", name=op.f("uq_subjects_name")),
        sa.UniqueConstraint("short_name", name=op.f("uq_subjects_short_name")),
    )
    op.create_table(
        "teachers",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("short_code", sa.String(length=10), nullable=False),
        sa.Column("max_hours_per_week", sa.SmallInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teachers")),
        sa.UniqueConstraint("short_code", name=op.f("uq_teachers_short_code")),
    )
    op.create_table(
        "week_schemes",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_week_schemes")),
        sa.UniqueConstraint("name", name=op.f("uq_week_schemes_name")),
    )
    op.create_table(
        "room_subject_suitabilities",
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
            name=op.f("fk_room_subject_suitabilities_room_id_rooms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_room_subject_suitabilities_subject_id_subjects"),
        ),
        sa.PrimaryKeyConstraint(
            "room_id", "subject_id", name=op.f("pk_room_subject_suitabilities")
        ),
    )
    op.create_table(
        "school_classes",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("grade_level", sa.SmallInteger(), nullable=False),
        sa.Column("stundentafel_id", sa.Uuid(), nullable=False),
        sa.Column("week_scheme_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["stundentafel_id"],
            ["stundentafeln.id"],
            name=op.f("fk_school_classes_stundentafel_id_stundentafeln"),
        ),
        sa.ForeignKeyConstraint(
            ["week_scheme_id"],
            ["week_schemes.id"],
            name=op.f("fk_school_classes_week_scheme_id_week_schemes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_school_classes")),
        sa.UniqueConstraint("name", name=op.f("uq_school_classes_name")),
    )
    op.create_table(
        "stundentafel_entries",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("stundentafel_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("hours_per_week", sa.SmallInteger(), nullable=False),
        sa.Column("preferred_block_size", sa.SmallInteger(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["stundentafel_id"],
            ["stundentafeln.id"],
            name=op.f("fk_stundentafel_entries_stundentafel_id_stundentafeln"),
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_stundentafel_entries_subject_id_subjects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stundentafel_entries")),
        sa.UniqueConstraint(
            "stundentafel_id", "subject_id", name=op.f("uq_stundentafel_entries_stundentafel_id")
        ),
    )
    op.create_index(
        op.f("ix_stundentafel_entries_stundentafel_id"),
        "stundentafel_entries",
        ["stundentafel_id"],
        unique=False,
    )
    op.create_table(
        "teacher_qualifications",
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_teacher_qualifications_subject_id_subjects"),
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
            name=op.f("fk_teacher_qualifications_teacher_id_teachers"),
        ),
        sa.PrimaryKeyConstraint("teacher_id", "subject_id", name=op.f("pk_teacher_qualifications")),
    )
    op.create_table(
        "time_blocks",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("week_scheme_id", sa.Uuid(), nullable=False),
        sa.Column("day_of_week", sa.SmallInteger(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.ForeignKeyConstraint(
            ["week_scheme_id"],
            ["week_schemes.id"],
            name=op.f("fk_time_blocks_week_scheme_id_week_schemes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_time_blocks")),
        sa.UniqueConstraint(
            "week_scheme_id", "day_of_week", "position", name=op.f("uq_time_blocks_week_scheme_id")
        ),
    )
    op.create_index(
        op.f("ix_time_blocks_week_scheme_id"), "time_blocks", ["week_scheme_id"], unique=False
    )
    op.create_table(
        "class_groups",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("school_class_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("group_type", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["school_class_id"],
            ["school_classes.id"],
            name=op.f("fk_class_groups_school_class_id_school_classes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_class_groups")),
    )
    op.create_index(
        op.f("ix_class_groups_school_class_id"), "class_groups", ["school_class_id"], unique=False
    )
    op.create_table(
        "lessons",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("school_class_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=True),
        sa.Column("hours_per_week", sa.SmallInteger(), nullable=False),
        sa.Column("preferred_block_size", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["school_class_id"],
            ["school_classes.id"],
            name=op.f("fk_lessons_school_class_id_school_classes"),
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"], ["subjects.id"], name=op.f("fk_lessons_subject_id_subjects")
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"], ["teachers.id"], name=op.f("fk_lessons_teacher_id_teachers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lessons")),
        sa.UniqueConstraint(
            "school_class_id", "subject_id", name=op.f("uq_lessons_school_class_id")
        ),
    )
    op.create_index(
        op.f("ix_lessons_school_class_id"), "lessons", ["school_class_id"], unique=False
    )
    op.create_table(
        "room_availabilities",
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("time_block_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
            name=op.f("fk_room_availabilities_room_id_rooms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["time_block_id"],
            ["time_blocks.id"],
            name=op.f("fk_room_availabilities_time_block_id_time_blocks"),
        ),
        sa.PrimaryKeyConstraint("room_id", "time_block_id", name=op.f("pk_room_availabilities")),
    )
    op.create_table(
        "teacher_availabilities",
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("time_block_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
            name=op.f("fk_teacher_availabilities_teacher_id_teachers"),
        ),
        sa.ForeignKeyConstraint(
            ["time_block_id"],
            ["time_blocks.id"],
            name=op.f("fk_teacher_availabilities_time_block_id_time_blocks"),
        ),
        sa.PrimaryKeyConstraint(
            "teacher_id", "time_block_id", name=op.f("pk_teacher_availabilities")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("teacher_availabilities")
    op.drop_table("room_availabilities")
    op.drop_index(op.f("ix_lessons_school_class_id"), table_name="lessons")
    op.drop_table("lessons")
    op.drop_index(op.f("ix_class_groups_school_class_id"), table_name="class_groups")
    op.drop_table("class_groups")
    op.drop_index(op.f("ix_time_blocks_week_scheme_id"), table_name="time_blocks")
    op.drop_table("time_blocks")
    op.drop_table("teacher_qualifications")
    op.drop_index(
        op.f("ix_stundentafel_entries_stundentafel_id"), table_name="stundentafel_entries"
    )
    op.drop_table("stundentafel_entries")
    op.drop_table("school_classes")
    op.drop_table("room_subject_suitabilities")
    op.drop_table("week_schemes")
    op.drop_table("teachers")
    op.drop_table("subjects")
    op.drop_table("stundentafeln")
    op.drop_table("rooms")
    # ### end Alembic commands ###
