#!/usr/bin/env bash
# Regenerate solver/solver-core/benches/BASELINE.md.
#
# Runs the grundschule criterion bench, parses the fenced
# ---SOLVER-BENCH-BASELINE--- block from stderr, and renders the committed
# baseline markdown with a host-info footer. Idempotent: two runs on the
# same host overwrite the same file; only the numbers change.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${ROOT}/solver/solver-core/benches/BASELINE.md"
STDERR_FILE="$(mktemp)"
trap 'rm -f "${STDERR_FILE}"' EXIT

cd "${ROOT}"
cargo bench -p solver-core --bench solver_fixtures 2> "${STDERR_FILE}"

BLOCK="$(awk '/^---SOLVER-BENCH-BASELINE---$/{flag=1; next} /^---END---$/{flag=0} flag' "${STDERR_FILE}")"
if [[ -z "${BLOCK}" ]]; then
    echo "error: SOLVER-BENCH-BASELINE block not found in bench stderr" >&2
    cat "${STDERR_FILE}" >&2
    exit 1
fi

HEADER="$(printf '%s\n' "${BLOCK}" | head -n 1)"
EXPECTED_HEADER=$'fixture\tsamples\tp1_us\tp50_us\tp99_us\tplacements_per_sec\ttotal_placements\ttotal_hard_violations\tsoft_score'
if [[ "${HEADER}" != "${EXPECTED_HEADER}" ]]; then
    echo "error: bench TSV header drift" >&2
    echo "expected: ${EXPECTED_HEADER}" >&2
    echo "got:      ${HEADER}" >&2
    exit 1
fi

ROWS="$(printf '%s\n' "${BLOCK}" | tail -n +2)"
if [[ -z "${ROWS}" ]]; then
    echo "error: bench TSV has no data rows" >&2
    exit 1
fi

CPU="$(awk -F': ' '/^model name/{print $2; exit}' /proc/cpuinfo 2>/dev/null || echo unknown)"
KERNEL="$(uname -r)"
RUSTC="$(rustc --version)"
DATE="$(date -Idate)"

{
    echo "# Solver bench baseline"
    echo
    echo "<!-- Regenerated by \`mise run bench:record\`. Do not hand-edit. -->"
    echo
    echo "| Fixture | Samples | p1 (µs) | p50 (µs) | p99 (µs) | Placements/sec | Placements | Hard violations | Soft score |"
    echo "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |"
    while IFS=$'\t' read -r FIXTURE SAMPLES P1 P50 P99 PPS PLACEMENTS HARD SOFT; do
        printf '| %s | %s | %s | %s | %s | %s | %s | %s | %s |\n' \
            "${FIXTURE}" "${SAMPLES}" "${P1}" "${P50}" "${P99}" "${PPS}" "${PLACEMENTS}" "${HARD}" "${SOFT}"
    done <<< "${ROWS}"
    echo
    echo "Refreshed ${DATE} on ${CPU}, Linux ${KERNEL}, ${RUSTC}."
    echo
    echo "Refresh with \`mise run bench:record\` when a PR intentionally changes solver"
    echo "performance. An accidental diff here is a review gate, not a feature."
    echo
    echo "See \`solver/CLAUDE.md\` (Bench workflow) for the 20% regression budget and the"
    echo "algorithm-phase PRs this baseline gates."
} > "${OUT}"

echo "wrote ${OUT}"
