#!/usr/bin/env bash
# Regenerate solver/solver-core/benches/BASELINE.md.
#
# Runs the grundschule criterion bench, parses the fenced
# ---SOLVER-BENCH-BASELINE--- block from stderr, and renders the committed
# baseline markdown with a host-info footer. Idempotent: two runs on the
# same host overwrite the same file; only the numbers change.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${ROOT}/solver/solver-core/benches/BASELINE.md"
STDERR_FILE="$(mktemp)"
trap 'rm -f "${STDERR_FILE}"' EXIT

cd "${ROOT}"
cargo bench -p solver-core --bench solver_grundschule 2> "${STDERR_FILE}"

BLOCK="$(awk '/^---SOLVER-BENCH-BASELINE---$/{flag=1; next} /^---END---$/{flag=0} flag' "${STDERR_FILE}")"
if [[ -z "${BLOCK}" ]]; then
    echo "error: SOLVER-BENCH-BASELINE block not found in bench stderr" >&2
    cat "${STDERR_FILE}" >&2
    exit 1
fi

get() {
    local key="$1"
    local line
    line="$(awk -v k="${key}" -F'\t' '$1 == k {print $2}' <<< "${BLOCK}")"
    if [[ -z "${line}" ]]; then
        echo "error: key ${key} missing from bench output" >&2
        exit 1
    fi
    printf '%s' "${line}"
}

FIXTURE="$(get fixture)"
SAMPLES="$(get samples)"
P1="$(get p1_us)"
P50="$(get p50_us)"
P99="$(get p99_us)"
PPS="$(get placements_per_sec)"
PLACEMENTS="$(get total_placements)"
HARD="$(get total_hard_violations)"

CPU="$(awk -F': ' '/^model name/{print $2; exit}' /proc/cpuinfo 2>/dev/null || echo unknown)"
KERNEL="$(uname -r)"
RUSTC="$(rustc --version)"
DATE="$(date -Idate)"

cat > "${OUT}" <<EOF
# Solver bench baseline

<!-- Regenerated by \`mise run bench:record\`. Do not hand-edit. -->

| Fixture | Samples | p1 (µs) | p50 (µs) | p99 (µs) | Placements/sec | Placements | Hard violations |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| ${FIXTURE} | ${SAMPLES} | ${P1} | ${P50} | ${P99} | ${PPS} | ${PLACEMENTS} | ${HARD} |

Refreshed ${DATE} on ${CPU}, Linux ${KERNEL}, ${RUSTC}.

Refresh with \`mise run bench:record\` when a PR intentionally changes solver
performance. An accidental diff here is a review gate, not a feature.

See \`solver/CLAUDE.md\` (Bench workflow) for the 20% regression budget and the
algorithm-phase PRs this baseline gates.
EOF

echo "wrote ${OUT}"
